# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: [ Subconvert ]

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Print Action
      run: 'echo "event: ${{ github.event.action }}"'
    - uses: actions/checkout@v1
    - name: Subconvert
      if: github.event.action == 'Subconvert'
      run: |
        echo "event: ${{ github.event.action }}"
        echo "Done"
