# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: [ Subconvert ]

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Subconvert
      uses: actions/checkout@v1
    - run: 'echo "event: ${{ toJson(github.event) }}"'
    - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
    - run: echo "Done"
