# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: [ Subconvert ]

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Print Action
      run: 'echo "event: ${{ github.event.action }}"'
    - uses: actions/checkout@v1
    - name: Subconvert
      if: github.event.action == 'Subconvert'
      run: |
        curl 'http://198.181.41.37:25500/sub?target=clash&insert=false&config=configs%2Fyussicaex.ini&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true&upload=true'
        curl 'http://198.181.41.37:25500/sub?target=quan&insert=false&config=configs%2Fyussicaex.ini&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true&upload=true'
        curl 'http://198.181.41.37:25500/sub?target=quanx&insert=false&config=configs%2Fyussicaex.ini&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true&upload=true'
        echo "Done"
